# Generated by Django 4.2.2 on 2023-06-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_contractor_customuser_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contractor',
        ),
    ]
