# Generated by Django 4.2.2 on 2023-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ManyToManyField(blank=True, null=True, to='timesheet.contractor'),
        ),
    ]
