# Generated by Django 4.2.2 on 2023-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_remove_project_contractor_project_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ManyToManyField(blank=True, to='timesheet.contractor'),
        ),
    ]
