# Generated by Django 4.2.2 on 2023-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_rename_customer_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timesheet.project'),
        ),
    ]
